### ISSUE TITLE
Error retrieving Operating System info on Windows

### ISSUE THREAD

**Issue by RDCH106** [suhanna/System_info#4]
Library calls the following command with subprocess to retieve Operating System info:

```bash
'systeminfo | findstr /B /C:"OS Name"'
```
This is not correct because `systeminfo` on Windows dependes on OS language. For example, I use Windows OS in spanish and never will find the string `OS Name` because in spanish shows `Nombre del sistema operativo` instead of `OS Name`.

**Comment by RDCH106** [comment]
I propose at least returning platform and version provided by python built-in libraries:

```python
import platform

print(platform.system())
print(platform.release())
```

**Comment by suhanna** [comment]
Merged +1:
